# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /post/:title

# Setup
title: "Adrian Brink"
description: "Towards radical decentralization!"
url: https://adrianbrink.com
baseurl: "/"

author:
  name: "Adrian Brink"

# Custom vars
twitter: https://twitter.com/adrian_brink
github: https://github.com/adrianbrink
