title: Adrian's Website
description: "On a road to radical decentralization!"
author:
  name: "Adrian Brink"
  email: "adrian@officium.dev"
  url: "https//adrianbrink.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Adrian Brink"
year : "2020"
