# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adrian Brink
email: adrian@brink-holdings.com

#write html inside the double quotes to display in jumbotron
description: "<h1>Adrian Brink</h1><h3>The things I built, the projects I am working on, and the ideas I have not yet tackled.</h3>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adrianbrink.com" # the base hostname & protocol for your site
twitter_username: adrian_brink
github_username:  adrianbrink

# Build settings
markdown: kramdown
